
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author CL3-PC35
 */
public class NewJFrame5 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame5
     */
    public NewJFrame5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player1 = new javax.swing.JTextField();
        player2 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        player1.setText("0");
        getContentPane().add(player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 89, 32));

        player2.setText("0");
        getContentPane().add(player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 83, 32));

        txt1.setText("1");
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 70, 40));

        txt2.setText("1");
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 70, 40));

        txt3.setText("1");
        getContentPane().add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 70, 40));

        txt4.setText("1");
        getContentPane().add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 60, 40));

        txt5.setText("1");
        getContentPane().add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 60, 40));

        txt6.setText("1");
        getContentPane().add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 60, 40));

        txt7.setText("1");
        getContentPane().add(txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 60, 40));

        txt8.setText("1");
        getContentPane().add(txt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 60, 40));

        txt9.setText("1");
        getContentPane().add(txt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 60, 40));

        jLabel1.setFont(new java.awt.Font("Goudy Stout", 1, 14)); // NOI18N
        jLabel1.setText("PLAYER1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Goudy Stout", 1, 14)); // NOI18N
        jLabel2.setText("PLAYER2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Felix Titling", 3, 12)); // NOI18N
        jLabel3.setText("SCORE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Felix Titling", 3, 12)); // NOI18N
        jLabel4.setText("SCORE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jButton1.setText("CHECK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int Player1 = Integer.parseInt(player1.getText());
        int Player2 = Integer.parseInt(player2.getText());
        int box1 = Integer.parseInt(txt1.getText());
        int box2 = Integer.parseInt(txt2.getText());
        int box3 = Integer.parseInt(txt3.getText());
        int box4 = Integer.parseInt(txt4.getText());
        int box5 = Integer.parseInt(txt5.getText());
        int box6 = Integer.parseInt(txt6.getText());
        int box7 = Integer.parseInt(txt7.getText());
        int box8 = Integer.parseInt(txt8.getText());
        int box9 = Integer.parseInt(txt9.getText());
        
        
        
        
        
        
        if (box1 == 1 && box2 == 1 && box3 == 1) {
        int hb = Player1 + 1 ;
        player1.setText(""+hb);
        }
        
        else if (box4 == 1 && box5 == 1 && box6 ==1) {
        int hb = Player1 + 1 ;
        player1.setText(""+hb);
        }
        
         else if (box7 == 1 && box8 == 1 && box9 ==1) {
        int hb = Player1 + 1 ;
        player1.setText(""+hb);
        }
        
         else if (box1 == 0 && box2 == 0 && box3 ==0) {
       int hb = Player1 + 1 ;
        player1.setText(""+hb);
        }
        
         else if (box4 == 0 && box5 == 0 && box6 ==0) {
        int hb = Player1 + 1 ;
        player1.setText(""+hb);
        }
        
         else if(box7 == 0 && box8 == 0 && box9 ==0) {
        int hb = Player1 + 1 ;
        player1.setText(""+hb);
        }
        
          else
        {
        JOptionPane.showMessageDialog(null, "Invalid", "Result", JOptionPane.INFORMATION_MESSAGE);
        }
        
         
        
        
                
                
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField player1;
    private javax.swing.JTextField player2;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    // End of variables declaration//GEN-END:variables
}
